name: toybox CI

on:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  MacOS-10_15:
    runs-on: macos-10.15

    steps:

    - name: Install libgit2
      run: brew install libgit2
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Build
      run: zig build
    - name: Test
      run: VERBOSE=1 make tests

  Ubuntu-20_04:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout libgit2
      uses: actions/checkout@master
      with:
        repository: libgit2/libgit2
        path: libgit2

    - name: Configure cmake
      run: cmake --configure .
      working-directory: libgit2
  
    - name: Build and Install libgit2
      run: sudo cmake --build . --target install
      working-directory: libgit2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master

    - name: Checkout Zkg
      uses: actions/checkout@master
      with:
        repository: mattnite/zkg
        submodules: recursive
        path: zkg

    - name: Build Zkg
      run: zig build
      working-directory: zkg
    
    - uses: actions/checkout@master
      with:
        path: zigbox
    - run: ../zkg/zig-cache/zkg fetch
      working-directory: zigbox
    - name: Build
      run: zig build
      working-directory: zigbox
    - name: Test
      run: VERBOSE=1 make tests
      working-directory: zigbox
